### ISSUE TITLE
Operator creates pods with image tag `latest` despite setting a version in the CRD

### ISSUE THREAD

**Issue by WoodyWoodsta** [formancehq/stack#1621]
I have Formance deployed using the following spec:

```yaml
apiVersion: formance.com/v1beta1
kind: Stack
metadata:
  name: my-stack
spec:
  versionsFromFile: v2.0.2
---
apiVersion: formance.com/v1beta1
kind: Ledger
metadata:
  name: my-stack
spec:
  stack: my-stack
```

However, I've noticed that the ledger pod is created with the `latest` tag for the container image. This means that if the pod is restarted, it will download the latest one and the schema will possibly be out of date.

We came across this because the above happened and all of a sudden the API was returning `OUTDATED_SCHEMA`.

**Comment by WoodyWoodsta** [comment]
Ok - I think I understand what my issue is.

I should have been using the `version` property. The documentation [here](https://docs.formance.com/operator/Modules/Stack#stack-object) has an error in the example.

**Comment by flemzord** [comment]
Hello @WoodyWoodsta 
Does the v2.0.2 file exist in the version CRD on your Kubernetes cluster?

**Comment by WoodyWoodsta** [comment]
Hey @flemzord. My issue was a misunderstanding of `versionsFromFile`, which appears to need to exist somehow as a file/configmap.

I've set `version` instead, and the pods have the required label.

In the example in the documentation linked above, the `versionsFromFile` property has what I understand should be set on `version`, as the tag.

**Comment by flemzord** [comment]
Indeed, when you deploy the Operator with our Helm chart, we automatically create in the CRD `versions.formance.com` the versions supported by the Operator. 
In your case, you can use version “v2.0” instead of v2.0.4. 


```
apiVersion: formance.com/v1beta1
kind: Stack
metadata:
  name: my-stack
spec:
  versionsFromFile: v2.0
---
apiVersion: formance.com/v1beta1
kind: Ledger
metadata:
  name: my-stack
spec:
  stack: my-stack
  ```
